"use client";
import { Inter } from "next/font/google";
import "../scss/index.scss";
import React, { useRef, useState } from "react";
import { Canvas, useFrame } from "@react-three/fiber";
import {
  EffectComposer,
  N8AO,
  Bloom,
  Noise,
} from "@react-three/postprocessing";
import Scene from "../components/scene";

const inter = Inter({ subsets: ["latin"] });

/*export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/

function Box(props) {
  // This reference will give us direct access to the mesh
  const meshRef = useRef();
  // Set up state for the hovered and active state
  const [hovered, setHover] = useState(false);
  const [active, setActive] = useState(false);
  // Subscribe this component to the render-loop, rotate the mesh every frame
  useFrame((state, delta) => (meshRef.current.rotation.x += delta));
  // Return view, these are regular three.js elements expressed in JSX
  return (
    <mesh
      {...props}
      ref={meshRef}
      scale={active ? 1.5 : 1}
      onClick={(event) => setActive(!active)}
      onPointerOver={(event) => setHover(true)}
      onPointerOut={(event) => setHover(false)}
    >
      <boxGeometry args={[1, 1, 1]} />
      <meshStandardMaterial color={hovered ? "hotpink" : "orange"} />
    </mesh>
  );
}
//<ambientLight intensity={2} color={"#DBE1E0"} />
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="h-dvh">
          <Canvas shadows dpr={[1, 1.5]}>
            <color attach="background" args={["#DBE1E0"]} />
            <hemisphereLight
              color="#DBE1E0"
              groundColor="#B6BAB1"
              position={[-7, 25, 13]}
              intensity={3.5}
            />
            <fog attach="fog" args={["#DBE1E0", 10, 40]} />
            <directionalLight
              name="light"
              intensity={1}
              color="#dbe1e0"
              position={[2.24, 5.29, 4.57]}
              rotation={[-0.86, 0.31, -1.18]}
            />
            <Scene />
            <EffectComposer disableNormalPass>
              <N8AO aoRadius={3} distanceFalloff={2} intensity={1} />

              <Noise opacity={0.02} />
            </EffectComposer>
            {children}
          </Canvas>
        </main>
      </body>
    </html>
  );
}
