/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef, useMemo, useContext, createContext } from "react";
import { useGLTF, Merged, useTexture } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import CustomShaderMaterial from "three-custom-shader-material/vanilla";
import leafsVertexShader from "../../shaders/leafs/vertex.glsl";
import leafsFragmentShader from "../../shaders/leafs/fragment.glsl";
import { useFrame } from "@react-three/fiber";

type GLTFResult = GLTF & {
  nodes: {
    bush001: THREE.Mesh;
  };
};

const context = createContext();

const leafsMaterial = new CustomShaderMaterial({
  baseMaterial: THREE.MeshPhysicalMaterial,
  vertexShader: leafsVertexShader,
  fragmentShader: leafsFragmentShader,
  uniforms: {
    uTime: { value: 0 },
    uWindStrenght: { value: 1 },
    uColor: { value: new THREE.Color("#55cd62") },
  },
  transparent: true,
  transmission: 0,
  thickness: 0.004,
  metalness: 0,
  alphaTest: 0.1,
});

export function BushInstances({ children, ...props }) {
  const { nodes } = useGLTF("/assets/bush.glb") as GLTFResult;
  const [leafsTexture] = useTexture(["assets/textures/T_leaf.png"]);

  const instances = useMemo(() => {
    leafsMaterial.alphaMap = leafsTexture;

    nodes.bush001.material = leafsMaterial;

    return {
      Bush: nodes.bush001,
    };
  }, [nodes, leafsTexture]);

  useFrame(({ clock }) => {
    leafsMaterial.uniforms.uTime.value = clock.getElapsedTime();
  });

  return (
    <Merged
      meshes={instances}
      {...props}
    >
      {(instances) => (
        <context.Provider
          value={instances}
          children={children}
        />
      )}
    </Merged>
  );
}

export function Bush(props: JSX.IntrinsicElements["group"]) {
  const instances = useContext(context);

  return (
    <group
      {...props}
      dispose={null}
    >
      <instances.Bush scale={0.3}>
        <meshBasicMaterial color="red" />
      </instances.Bush>
    </group>
  );
}

useGLTF.preload("/assets/bush.glb");
