/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef, useMemo, useContext, createContext } from "react";
import { useGLTF, Merged, PerspectiveCamera } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Plane011: THREE.Mesh;
    Plane011_1: THREE.Mesh;
    Plane011: THREE.Mesh;
    Plane011_1: THREE.Mesh;
    Cube053: THREE.Mesh;
    Cube053_1: THREE.Mesh;
    Cube053: THREE.Mesh;
    Cube053_1: THREE.Mesh;
    Plane011: THREE.Mesh;
    Plane011_1: THREE.Mesh;
    Plane011: THREE.Mesh;
    Plane011_1: THREE.Mesh;
    Plane011: THREE.Mesh;
    Plane011_1: THREE.Mesh;
    Cube053: THREE.Mesh;
    Cube053_1: THREE.Mesh;
    Plane011: THREE.Mesh;
    Plane011_1: THREE.Mesh;
    Plane011: THREE.Mesh;
    Plane011_1: THREE.Mesh;
    Plane011: THREE.Mesh;
    Plane011_1: THREE.Mesh;
    Cube053: THREE.Mesh;
    Cube053_1: THREE.Mesh;
    Plane011: THREE.Mesh;
    Plane011_1: THREE.Mesh;
    Plane011: THREE.Mesh;
    Plane011_1: THREE.Mesh;
    Cube053: THREE.Mesh;
    Cube053_1: THREE.Mesh;
    Plane011: THREE.Mesh;
    Plane011_1: THREE.Mesh;
    Plane011: THREE.Mesh;
    Plane011_1: THREE.Mesh;
    Cube053: THREE.Mesh;
    Cube053_1: THREE.Mesh;
    Cylinder_1: THREE.Mesh;
    Cylinder_2: THREE.Mesh;
    Plane002: THREE.Mesh;
    Plane003: THREE.Mesh;
    Cylinder002: THREE.Mesh;
    Cube024_1: THREE.Mesh;
    Cube024_2: THREE.Mesh;
    Cube023: THREE.Mesh;
    Cube024: THREE.Mesh;
    Cube025: THREE.Mesh;
    Plane001: THREE.Mesh;
    Plane017: THREE.Mesh;
    Cube027: THREE.Mesh;
    Cube029: THREE.Mesh;
    Cube010: THREE.Mesh;
    Cylinder001: THREE.Mesh;
    Sphere: THREE.Mesh;
    Cube030: THREE.Mesh;
    Cube032: THREE.Mesh;
    Cube034: THREE.Mesh;
    Cube039: THREE.Mesh;
    Cube042: THREE.Mesh;
    Plane011: THREE.Mesh;
    Plane011_1: THREE.Mesh;
    Plane011: THREE.Mesh;
    Plane011_1: THREE.Mesh;
    Cube035: THREE.Mesh;
    Plane011: THREE.Mesh;
    Plane011_1: THREE.Mesh;
    Plane011: THREE.Mesh;
    Plane011_1: THREE.Mesh;
    Cube011: THREE.Mesh;
    Cube012: THREE.Mesh;
    Cube013: THREE.Mesh;
    Cube014: THREE.Mesh;
    Cube015: THREE.Mesh;
    Cube016: THREE.Mesh;
    Cube017: THREE.Mesh;
    Cube022_1: THREE.Mesh;
    Cube022_2: THREE.Mesh;
    Cube023_1: THREE.Mesh;
    Cube023_2: THREE.Mesh;
    Cube022_1: THREE.Mesh;
    Cube022_2: THREE.Mesh;
    Cube022_1: THREE.Mesh;
    Cube022_2: THREE.Mesh;
    Cube036: THREE.Mesh;
    Cube031: THREE.Mesh;
    Cube031_1: THREE.Mesh;
    Cube031_2: THREE.Mesh;
    Cube031_3: THREE.Mesh;
    Cube031_4: THREE.Mesh;
    Cube031_5: THREE.Mesh;
    Cylinder003: THREE.Mesh;
    Cube028: THREE.Mesh;
    Cube045: THREE.Mesh;
    Cube046: THREE.Mesh;
    Cube047: THREE.Mesh;
    Cube048: THREE.Mesh;
    Cube037: THREE.Mesh;
    Cube033: THREE.Mesh;
    Cube033_1: THREE.Mesh;
    Cube033_2: THREE.Mesh;
    Cube033_3: THREE.Mesh;
    Cube036_1: THREE.Mesh;
    Cube036_2: THREE.Mesh;
    Cube036_3: THREE.Mesh;
    Plane004: THREE.Mesh;
    Plane008: THREE.Mesh;
    Plane009: THREE.Mesh;
    plant: THREE.Mesh;
    plant001: THREE.Mesh;
    plant002: THREE.Mesh;
    plant003: THREE.Mesh;
    plant004: THREE.Mesh;
    plant005: THREE.Mesh;
    plant006: THREE.Mesh;
    plant007: THREE.Mesh;
    BézierCurve008: THREE.Mesh;
    BézierCurve008_1: THREE.Mesh;
    BézierCurve008: THREE.Mesh;
    BézierCurve008_1: THREE.Mesh;
    BézierCurve008: THREE.Mesh;
    BézierCurve008_1: THREE.Mesh;
    BézierCurve008: THREE.Mesh;
    BézierCurve008_1: THREE.Mesh;
    BézierCurve008: THREE.Mesh;
    BézierCurve008_1: THREE.Mesh;
    BézierCurve008: THREE.Mesh;
    BézierCurve008_1: THREE.Mesh;
    BézierCurve008: THREE.Mesh;
    BézierCurve008_1: THREE.Mesh;
    BézierCurve008: THREE.Mesh;
    BézierCurve008_1: THREE.Mesh;
    Plane010: THREE.Mesh;
  };
  materials: {};
};

const context = createContext();
export function IslandInstances({ children, ...props }) {
  const { nodes } = useGLTF("/assets/island_rebuild.glb") as GLTFResult;
  const instances = useMemo(
    () => ({
      Plane: nodes.Plane011,
      Plane1: nodes.Plane011_1,
      Cube: nodes.Cube053,
      Cube1: nodes.Cube053_1,
      Cylinder: nodes.Cylinder_1,
      Cylinder1: nodes.Cylinder_2,
      Plane2: nodes.Plane002,
      Plane3: nodes.Plane003,
      Cylinder2: nodes.Cylinder002,
      Cube2: nodes.Cube024_1,
      Cube3: nodes.Cube024_2,
      Cube4: nodes.Cube023,
      Cube5: nodes.Cube024,
      Cube6: nodes.Cube025,
      Plane4: nodes.Plane001,
      Plane5: nodes.Plane017,
      Cube7: nodes.Cube027,
      Cube8: nodes.Cube029,
      Cube9: nodes.Cube010,
      Cylinder3: nodes.Cylinder001,
      Sphere: nodes.Sphere,
      Cube10: nodes.Cube030,
      Cube11: nodes.Cube032,
      Cube12: nodes.Cube034,
      Cube13: nodes.Cube039,
      Cube14: nodes.Cube042,
      Cube15: nodes.Cube035,
      Cube16: nodes.Cube011,
      Cube17: nodes.Cube012,
      Cube18: nodes.Cube014,
      Cube19: nodes.Cube017,
      Cube20: nodes.Cube022_1,
      Cube21: nodes.Cube022_2,
      Cube22: nodes.Cube023_1,
      Cube23: nodes.Cube023_2,
      Cube24: nodes.Cube036,
      Cube25: nodes.Cube031,
      Cube26: nodes.Cube031_1,
      Cube27: nodes.Cube031_2,
      Cube28: nodes.Cube031_3,
      Cube29: nodes.Cube031_4,
      Cube30: nodes.Cube031_5,
      Cylinder4: nodes.Cylinder003,
      Cube31: nodes.Cube037,
      Cube32: nodes.Cube033,
      Cube33: nodes.Cube033_1,
      Cube34: nodes.Cube033_2,
      Cube35: nodes.Cube033_3,
      Cube36: nodes.Cube036_1,
      Cube37: nodes.Cube036_2,
      Cube38: nodes.Cube036_3,
      Plane6: nodes.Plane004,
      Plane7: nodes.Plane008,
      Plane8: nodes.Plane009,
      Plant: nodes.plant,
      BzierCurve: nodes.BézierCurve008,
      BzierCurve1: nodes.BézierCurve008_1,
      Plane9: nodes.Plane010,
    }),
    [nodes]
  );
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => (
        <context.Provider value={instances} children={children} />
      )}
    </Merged>
  );
}

export function Island(props: JSX.IntrinsicElements["group"]) {
  const instances = useContext(context);
  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera
        makeDefault
        far={100}
        near={0.1}
        fov={22.895}
        position={[7.831, 5.934, 6.61]}
        rotation={[-0.639, 0.773, 0.479]}
      />
      <group
        position={[-0.973, 0, 0.964]}
        rotation={[0, -0.572, 0]}
        scale={0.232}
      >
        <instances.Plane />
        <instances.Plane1 />
      </group>
      <group
        position={[-0.41, 0, 1.218]}
        rotation={[-Math.PI, 0.557, -Math.PI]}
        scale={[0.264, 0.093, 0.264]}
      >
        <instances.Plane />
        <instances.Plane1 />
      </group>
      <group
        position={[-0.427, 0.318, 0.847]}
        rotation={[-Math.PI, 0.686, -Math.PI]}
        scale={[0.332, 0.252, 0.332]}
      >
        <instances.Cube />
        <instances.Cube1 />
      </group>
      <group
        position={[0.151, -0.108, 1.207]}
        rotation={[0, 0.732, 0]}
        scale={[0.332, 0.252, 0.332]}
      >
        <instances.Cube />
        <instances.Cube1 />
      </group>
      <group
        position={[0.069, 0.306, 0.834]}
        rotation={[0, 0.791, 0]}
        scale={[0.264, 0.158, 0.264]}
      >
        <instances.Plane />
        <instances.Plane1 />
      </group>
      <group
        position={[-0.391, 0.329, 0.837]}
        rotation={[Math.PI, -0.116, Math.PI]}
        scale={[0.264, 0.149, 0.264]}
      >
        <instances.Plane />
        <instances.Plane1 />
      </group>
      <group
        position={[-0.549, 0.26, 1.158]}
        rotation={[-Math.PI, 0.295, -Math.PI]}
        scale={[0.117, 0.149, 0.117]}
      >
        <instances.Plane />
        <instances.Plane1 />
      </group>
      <group
        position={[0.654, -0.108, 0.478]}
        rotation={[Math.PI, -1.201, 0]}
        scale={[-0.332, -0.405, -0.332]}
      >
        <instances.Cube />
        <instances.Cube1 />
      </group>
      <group
        position={[0.335, -0.005, 0.707]}
        rotation={[0, 0.791, 0]}
        scale={[0.264, 0.124, 0.264]}
      >
        <instances.Plane />
        <instances.Plane1 />
      </group>
      <group
        position={[0.348, 0.248, 0.363]}
        rotation={[Math.PI, -1.099, Math.PI]}
        scale={[0.264, 0.172, 0.264]}
      >
        <instances.Plane />
        <instances.Plane1 />
      </group>
      <group
        position={[0.42, 0.065, -0.766]}
        rotation={[0, -1.486, 0]}
        scale={[0.264, 0.225, 0.264]}
      >
        <instances.Plane />
        <instances.Plane1 />
      </group>
      <group
        position={[0.34, 0.183, -0.155]}
        rotation={[0, 1.47, -Math.PI]}
        scale={[-0.377, -0.405, -0.332]}
      >
        <instances.Cube />
        <instances.Cube1 />
      </group>
      <group
        position={[-0.5, 0.767, -0.751]}
        rotation={[Math.PI, -1.019, Math.PI]}
        scale={[0.264, 0.112, 0.264]}
      >
        <instances.Plane />
        <instances.Plane1 />
      </group>
      <group
        position={[-0.617, 0.859, -0.224]}
        rotation={[-Math.PI, 1.511, -Math.PI]}
        scale={[0.264, 0.094, 0.264]}
      >
        <instances.Plane />
        <instances.Plane1 />
      </group>
      <group
        position={[-0.722, 0.823, 0.596]}
        rotation={[0, 1.377, -Math.PI]}
        scale={[-0.346, -0.2, -0.304]}
      >
        <instances.Cube />
        <instances.Cube1 />
      </group>
      <group
        position={[-0.84, 0.68, 0.752]}
        rotation={[0, 1.095, 0]}
        scale={[0.28, 0.147, 0.382]}
      >
        <instances.Plane />
        <instances.Plane1 />
      </group>
      <group
        position={[-0.999, 1.206, 0.684]}
        rotation={[0, -1.57, 0]}
        scale={[0.2, 0.044, 0.273]}
      >
        <instances.Plane />
        <instances.Plane1 />
      </group>
      <group
        position={[-0.392, 0.668, 0.126]}
        rotation={[0, -1.507, -Math.PI]}
        scale={[-0.346, -0.295, -0.304]}
      >
        <instances.Cube />
        <instances.Cube1 />
      </group>
      <group
        position={[-1.054, 0.383, 0.2]}
        rotation={[0, Math.PI / 8, 0]}
        scale={[0.328, 0.873, 0.328]}
      >
        <instances.Cylinder />
        <instances.Cylinder1 />
      </group>
      <instances.Plane2 position={[0, 0.91, 0]} scale={[0.595, 0.795, 0.795]} />
      <instances.Plane3
        position={[0.719, -0.056, 0.801]}
        rotation={[0, 0.834, 0]}
        scale={[1.115, 1, 1]}
      />
      <instances.Cylinder2
        position={[-1.054, 0.469, 0.2]}
        scale={[0.916, 1, 0.916]}
      />
      <group
        position={[-0.606, 1.205, -0.252]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.247, 0.228, 0.336]}
      >
        <instances.Cube2 />
        <instances.Cube3 />
      </group>
      <instances.Cube4
        position={[-0.606, 1.205, -0.252]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.247, 0.228, 0.361]}
      />
      <instances.Cube5
        position={[-0.606, 1.205, -0.252]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.247, 0.228, 0.361]}
      />
      <instances.Cube6
        position={[-0.514, 1.19, -0.448]}
        scale={[0.131, 0.015, 0.015]}
      />
      <instances.Plane4
        position={[-3.292, 3.272, -0.312]}
        scale={[1, 1.484, 1]}
      />
      <instances.Plane5
        position={[-0.325, 1.54, -0.581]}
        rotation={[0, 0, -0.247]}
        scale={[0.118, 0.159, 0.106]}
      />
      <instances.Cube7
        position={[-0.606, 1.205, -0.252]}
        scale={[0.013, 0.012, 0.012]}
      />
      <instances.Cube8
        position={[-0.705, 0.925, 0.179]}
        scale={[0.238, 0.151, 0.31]}
      />
      <instances.Cube9
        position={[-1.054, 2.86, 0.2]}
        scale={[0.003, 0.149, 0.003]}
      />
      <instances.Cylinder3
        position={[-1.054, 2.519, 0.2]}
        scale={[0.926, 1, 0.926]}
      />
      <instances.Sphere
        position={[-1.054, 2.544, 0.2]}
        scale={[0.158, 0.171, 0.158]}
      />
      <instances.Cube10
        position={[-0.176, 0.925, 0.387]}
        scale={[0.238, 0.151, 0.102]}
      />
      <instances.Cube11
        position={[-0.192, 0.773, 0.094]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.238, 0.151, 0.078]}
      />
      <instances.Cube12 position={[-0.176, 0.925, 0.387]} />
      <instances.Cube13
        position={[0.761, 0.238, -0.514]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <instances.Cube14
        position={[0.989, -0.159, 0.107]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.238, 0.151, 0.114]}
      />
      <group
        position={[0.654, -0.079, -0.139]}
        rotation={[0, -1.396, 0]}
        scale={[0.264, 0.123, 0.264]}
      >
        <instances.Plane />
        <instances.Plane1 />
      </group>
      <group
        position={[0.774, -0.079, 0.325]}
        rotation={[0, 0.727, 0]}
        scale={[0.128, 0.182, 0.166]}
      >
        <instances.Plane />
        <instances.Plane1 />
      </group>
      <instances.Cube15 position={[0.813, 0.767, 0.189]} />
      <group
        position={[1.009, -0.165, -0.677]}
        rotation={[-Math.PI, 0.893, -Math.PI]}
        scale={[0.193, 0.135, 0.193]}
      >
        <instances.Plane />
        <instances.Plane1 />
      </group>
      <group
        position={[0.75, -0.165, -0.703]}
        rotation={[Math.PI, -0.134, Math.PI]}
        scale={[0.135, 0.135, 0.139]}
      >
        <instances.Plane />
        <instances.Plane1 />
      </group>
      <instances.Cube16
        position={[-0.858, 1.577, 0.337]}
        rotation={[3.072, 0.835, -3.09]}
        scale={[-0.011, -0.011, -0.021]}
      />
      <instances.Cube17
        position={[-0.893, 1.582, 0.369]}
        rotation={[-0.069, -0.835, -0.052]}
        scale={[0.011, 0.011, 0.021]}
      />
      <instances.Cube16
        position={[-0.837, 1.892, 0.149]}
        rotation={[-0.017, -0.054, 0.099]}
        scale={[0.009, 0.009, 0.017]}
      />
      <instances.Cube18
        position={[-0.878, 1.309, 0.375]}
        rotation={[-0.069, -0.835, -0.052]}
        scale={[0.01, 0.01, 0.02]}
      />
      <instances.Cube17
        position={[-1.074, 1.715, 0.427]}
        rotation={[-2.402, -1.502, -2.403]}
        scale={[0.009, 0.009, 0.019]}
      />
      <instances.Cube17
        position={[-0.999, 1.415, 0.445]}
        rotation={[-1.171, 1.439, 1.177]}
        scale={[-0.011, -0.011, -0.021]}
      />
      <instances.Cube19
        position={[-1.022, 2.082, 0.408]}
        rotation={[-1.25, 1.413, 1.259]}
        scale={[-0.009, -0.009, -0.018]}
      />
      <group position={[-0.824, 1.652, 0.2]}>
        <instances.Cube20 />
        <instances.Cube21 />
      </group>
      <group position={[-1.054, 1.652, 0.43]} rotation={[0, -Math.PI / 2, 0]}>
        <instances.Cube22 />
        <instances.Cube23 />
      </group>
      <group position={[-0.844, 1.99, 0.2]} scale={0.725}>
        <instances.Cube20 />
        <instances.Cube21 />
      </group>
      <group
        position={[-1.054, 1.99, 0.411]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.725}
      >
        <instances.Cube20 />
        <instances.Cube21 />
      </group>
      <instances.Cube24
        position={[-0.347, 1.521, -0.252]}
        rotation={[0, 0, -0.23]}
        scale={[0.021, 0.016, 0.012]}
      />
      <group
        position={[-0.371, 1.337, -0.252]}
        rotation={[0, 0, -0.1]}
        scale={[0.04, 0.017, 0.053]}
      >
        <instances.Cube25 />
        <instances.Cube26 />
      </group>
      <group
        position={[-0.371, 1.337, -0.064]}
        rotation={[0, 0, -0.1]}
        scale={[0.04, 0.017, 0.053]}
      >
        <instances.Cube27 />
        <instances.Cube28 />
      </group>
      <group
        position={[-0.371, 1.337, -0.439]}
        rotation={[0, 0, -0.1]}
        scale={[0.04, 0.017, 0.053]}
      >
        <instances.Cube29 />
        <instances.Cube30 />
      </group>
      <instances.Cylinder4
        position={[-1.054, 2.519, 0.2]}
        scale={[0.926, 1, 0.926]}
      />
      <instances.Cube16
        position={[-0.379, 1.267, 0.018]}
        rotation={[-0.029, -0.049, -0.125]}
        scale={[0.009, 0.009, 0.017]}
      />
      <instances.Cube16
        position={[-0.362, 1.417, -0.526]}
        rotation={[-0.029, -0.049, -0.125]}
        scale={[0.009, 0.009, 0.017]}
      />
      <instances.Cube16
        position={[-0.362, 1.457, -0.558]}
        rotation={[-0.029, -0.049, -0.125]}
        scale={[0.009, 0.009, 0.017]}
      />
      <instances.Cube16
        position={[-0.362, 1.476, -0.492]}
        rotation={[3.109, 0.049, 0.125]}
        scale={[0.009, 0.009, 0.017]}
      />
      <instances.Cube16
        position={[-0.374, 1.361, -0.18]}
        rotation={[3.113, 0.049, -3.017]}
        scale={[-0.009, -0.009, -0.017]}
      />
      <instances.Cube31
        position={[-0.585, 1.511, 0.087]}
        rotation={[0, 0, -0.092]}
        scale={[0.16, 0.009, 0.009]}
      />
      <group position={[-0.634, 1.314, 0.087]} scale={[0.054, 0.087, 0.054]}>
        <instances.Cube32 />
        <instances.Cube33 />
        <instances.Cube34 />
        <instances.Cube35 />
      </group>
      <group
        position={[-0.806, 1.314, 0.194]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.054, 0.087, 0.054]}
      >
        <instances.Cube36 />
        <instances.Cube37 />
        <instances.Cube38 />
      </group>
      <instances.Plane6
        position={[-0.585, 1.475, 0.088]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.07, 0.07, 0.042]}
      />
      <instances.Plane7 position={[0.144, 1.159, -0.585]} />
      <instances.Plane8 position={[-0.026, 0.973, 0.627]} />
      <instances.Plant
        position={[0.357, 0.945, -0.689]}
        rotation={[0.208, -0.258, -0.252]}
        scale={[0.02, 0.022, 0.018]}
      />
      <instances.Plant
        position={[0.46, 0.927, -0.205]}
        rotation={[0.307, -0.391, 0.021]}
        scale={[0.02, 0.022, 0.018]}
      />
      <instances.Plant
        position={[-0.06, 0.912, -0.488]}
        rotation={[0.096, -0.391, -0.032]}
        scale={[0.02, 0.022, 0.018]}
      />
      <instances.Plant
        position={[1.133, 0.357, -0.61]}
        rotation={[-0.105, -0.454, -0.655]}
        scale={[0.02, 0.022, 0.018]}
      />
      <instances.Plant
        position={[0.92, 0.357, -0.684]}
        rotation={[0.181, -0.342, -0.023]}
        scale={[0.02, 0.022, 0.018]}
      />
      <instances.Plant
        position={[1.041, 0.357, -0.788]}
        rotation={[-0.027, 0.015, -0.221]}
        scale={[0.02, 0.022, 0.018]}
      />
      <instances.Plant
        position={[0.847, 0.357, -0.805]}
        rotation={[-0.027, 0.015, -0.221]}
        scale={[0.02, 0.022, 0.018]}
      />
      <instances.Plant
        position={[0.763, 0.363, -0.738]}
        rotation={[0.793, 1.143, -1.05]}
        scale={[0.02, 0.022, 0.018]}
      />
      <group
        position={[-0.593, 1.171, -0.797]}
        rotation={[0, 0.1, 0]}
        scale={0.022}
      >
        <instances.BzierCurve />
        <instances.BzierCurve1 />
      </group>
      <group
        position={[1.02, 0.342, -0.722]}
        rotation={[0, 0.655, 0]}
        scale={0.017}
      >
        <instances.BzierCurve />
        <instances.BzierCurve1 />
      </group>
      <group
        position={[0.499, 0.911, -0.698]}
        rotation={[Math.PI, -0.413, Math.PI]}
        scale={0.022}
      >
        <instances.BzierCurve />
        <instances.BzierCurve1 />
      </group>
      <group
        position={[0.363, 0.899, -0.268]}
        rotation={[0, 1.201, 0]}
        scale={0.018}
      >
        <instances.BzierCurve />
        <instances.BzierCurve1 />
      </group>
      <group
        position={[0.138, 0.899, 0.91]}
        rotation={[-Math.PI, 0.059, -Math.PI]}
        scale={0.014}
      >
        <instances.BzierCurve />
        <instances.BzierCurve1 />
      </group>
      <group
        position={[-0.4, 0.869, 0.885]}
        rotation={[0, -0.347, 0]}
        scale={0.02}
      >
        <instances.BzierCurve />
        <instances.BzierCurve1 />
      </group>
      <group
        position={[-0.378, 0.752, 1.214]}
        rotation={[0, 0.565, 0]}
        scale={0.018}
      >
        <instances.BzierCurve />
        <instances.BzierCurve1 />
      </group>
      <group
        position={[0, 0.869, -0.713]}
        rotation={[0, -1.026, 0]}
        scale={0.022}
      >
        <instances.BzierCurve />
        <instances.BzierCurve1 />
      </group>
      <instances.Plane9
        position={[0.719, -0.056, 0.801]}
        rotation={[0, 0.834, 0]}
        scale={[1.115, 1, 1]}
      />
    </group>
  );
}

useGLTF.preload("/assets/island_rebuild.glb");
