/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef, useMemo, useContext, createContext } from "react";
import { useGLTF, Merged, PerspectiveCamera } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Cube049: THREE.Mesh;
    Cube051: THREE.Mesh;
    Cube052: THREE.Mesh;
    Cube053: THREE.Mesh;
    Cube054: THREE.Mesh;
    Cube055: THREE.Mesh;
    Cube056: THREE.Mesh;
    Cube057: THREE.Mesh;
    Cube013: THREE.Mesh;
    Cube013_1: THREE.Mesh;
    Cube014: THREE.Mesh;
    Cube014_1: THREE.Mesh;
    Cube013: THREE.Mesh;
    Cube013_1: THREE.Mesh;
    Cube035: THREE.Mesh;
    Cube035_1: THREE.Mesh;
    Cube013: THREE.Mesh;
    Cube013_1: THREE.Mesh;
    Cube063: THREE.Mesh;
    Cube064: THREE.Mesh;
    Cube065: THREE.Mesh;
    Cube066: THREE.Mesh;
    Cube067: THREE.Mesh;
    Cube068: THREE.Mesh;
    Cube069: THREE.Mesh;
    Cube070: THREE.Mesh;
    Cube071: THREE.Mesh;
    Cube072: THREE.Mesh;
    Cube073: THREE.Mesh;
    Cube074: THREE.Mesh;
    Cube052_1: THREE.Mesh;
    Cube052_2: THREE.Mesh;
    Cube076: THREE.Mesh;
    Cube052_3: THREE.Mesh;
    Cube052_4: THREE.Mesh;
    Cube052_5: THREE.Mesh;
    Cube052_6: THREE.Mesh;
    Cube079: THREE.Mesh;
    Cube056_1: THREE.Mesh;
    Cube056_2: THREE.Mesh;
    Cube056_3: THREE.Mesh;
    Cube056_4: THREE.Mesh;
    Cube057_1: THREE.Mesh;
    Cube057_2: THREE.Mesh;
    Cube057_3: THREE.Mesh;
    Cube082: THREE.Mesh;
    Cube083: THREE.Mesh;
    Cube084: THREE.Mesh;
    Cube085: THREE.Mesh;
    Cylinder004_1: THREE.Mesh;
    Cylinder004_2: THREE.Mesh;
    Cylinder005: THREE.Mesh;
    Cylinder006: THREE.Mesh;
    Cylinder007: THREE.Mesh;
    Plane011: THREE.Mesh;
    Plane012: THREE.Mesh;
    Plane013: THREE.Mesh;
    Plane014: THREE.Mesh;
    Plane016: THREE.Mesh;
    Plane018: THREE.Mesh;
    Plane019: THREE.Mesh;
    plant008: THREE.Mesh;
    plant009: THREE.Mesh;
    plant010: THREE.Mesh;
    plant011: THREE.Mesh;
    plant012: THREE.Mesh;
    plant013: THREE.Mesh;
    plant014: THREE.Mesh;
    plant015: THREE.Mesh;
    Sphere001: THREE.Mesh;
    terain1007: THREE.Mesh;
    terain1008: THREE.Mesh;
    terain1009: THREE.Mesh;
    terain1010: THREE.Mesh;
    terain1011: THREE.Mesh;
    terain1012: THREE.Mesh;
    terain2016: THREE.Mesh;
    terain2017: THREE.Mesh;
    terain2018: THREE.Mesh;
    terain2019: THREE.Mesh;
    terain2020: THREE.Mesh;
    terain2021: THREE.Mesh;
    terain2022: THREE.Mesh;
    terain2023: THREE.Mesh;
    terain2024: THREE.Mesh;
    terain2025: THREE.Mesh;
    terain2026: THREE.Mesh;
    terain2027: THREE.Mesh;
    terain2028: THREE.Mesh;
    terain2029: THREE.Mesh;
    terain2030: THREE.Mesh;
    terain2031: THREE.Mesh;
    BézierCurve001: THREE.Mesh;
    BézierCurve001_1: THREE.Mesh;
    BézierCurve001: THREE.Mesh;
    BézierCurve001_1: THREE.Mesh;
    BézierCurve001: THREE.Mesh;
    BézierCurve001_1: THREE.Mesh;
    BézierCurve001: THREE.Mesh;
    BézierCurve001_1: THREE.Mesh;
    BézierCurve001: THREE.Mesh;
    BézierCurve001_1: THREE.Mesh;
    BézierCurve001: THREE.Mesh;
    BézierCurve001_1: THREE.Mesh;
    BézierCurve001: THREE.Mesh;
    BézierCurve001_1: THREE.Mesh;
    BézierCurve001: THREE.Mesh;
    BézierCurve001_1: THREE.Mesh;
  };
  materials: {
    metal: THREE.MeshStandardMaterial;
    brick: THREE.MeshStandardMaterial;
    window: THREE.MeshStandardMaterial;
    WINDOW: THREE.MeshStandardMaterial;
    WOOD: THREE.MeshStandardMaterial;
    ["wood dark"]: THREE.MeshStandardMaterial;
    roofing: THREE.MeshStandardMaterial;
    concrete: THREE.MeshStandardMaterial;
    water: THREE.MeshStandardMaterial;
    Grass: THREE.MeshStandardMaterial;
    sand: THREE.MeshStandardMaterial;
    bush: THREE.MeshStandardMaterial;
    stone_blank: THREE.MeshStandardMaterial;
    ["M_Bark_01.002"]: THREE.MeshStandardMaterial;
  };
};
const mat = new THREE.MeshPhysicalMaterial({
  color: 0xff0000,
  side: THREE.DoubleSide,
});

const context = createContext();
export function IslandInstances({ children, ...props }) {
  const { nodes, materials } = useGLTF("/assets/island.glb") as GLTFResult;

  //nodes.Cube049.material = mat;
  //  nodes.Cube035.geometry.computeFaceNormals();
  //  console.log(nodes.Cube035.geometry);

  Object.keys(nodes).forEach((key) => {
    if (nodes[key].material && key.includes("terain")) {
      //nodes[key].geometry.computeFaceNormals();
    }
  });

  const instances = useMemo(
    () => ({
      Cube1: nodes.Cube051,
      Cube2: nodes.Cube013,
      Cube3: nodes.Cube013_1,
      Plant: nodes.plant008,
      Terain: nodes.terain1007,
      Terain1: nodes.terain2016,
      BzierCurve: nodes.BézierCurve001,
      BzierCurve1: nodes.BézierCurve001_1,
    }),
    [nodes]
  );

  return (
    <Merged meshes={instances} {...props}>
      {(instances) => (
        <context.Provider value={instances} children={children} />
      )}
    </Merged>
  );
}

export function Island(props: JSX.IntrinsicElements["group"]) {
  const instances = useContext(context);
  const { nodes, materials } = useGLTF("/assets/island.glb") as GLTFResult;

  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera
        makeDefault
        far={767.7}
        near={0.1}
        fov={22.895}
        position={[65.397, 56.717, 49.561]}
        rotation={[-0.526, 0.853, 0.412]}
        scale={22.985}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube049.geometry}
        material={materials.metal}
        position={[-24.234, 65.745, 4.597]}
        scale={[0.064, 3.429, 0.064]}
      />
      <instances.Cube1
        position={[-19.704, 36.213, 7.83]}
        rotation={[3.072, 0.835, -3.09]}
        scale={[-0.247, -0.247, -0.49]}
      />
      <instances.Cube1
        position={[-20.52, 36.328, 8.567]}
        rotation={[-0.069, -0.835, -0.052]}
        scale={[0.247, 0.247, 0.49]}
      />
      <instances.Cube1
        position={[-19.242, 43.479, 3.433]}
        rotation={[-0.017, -0.054, 0.099]}
        scale={[0.198, 0.198, 0.393]}
      />
      <instances.Cube1
        position={[-20.186, 30.078, 8.622]}
        rotation={[-0.069, -0.835, -0.052]}
        scale={[0.236, 0.236, 0.469]}
      />
      <instances.Cube1
        position={[-24.689, 39.41, 9.81]}
        rotation={[-2.402, -1.502, -2.403]}
        scale={[0.217, 0.217, 0.431]}
      />
      <instances.Cube1
        position={[-22.962, 32.535, 10.236]}
        rotation={[-1.171, 1.439, 1.177]}
        scale={[-0.247, -0.247, -0.491]}
      />
      <instances.Cube1
        position={[-23.5, 47.849, 9.369]}
        rotation={[-1.25, 1.413, 1.259]}
        scale={[-0.209, -0.209, -0.415]}
      />
      <group position={[-18.943, 37.966, 4.597]} scale={22.985}>
        <instances.Cube2 />
        <instances.Cube3 />
      </group>
      <group
        position={[-24.234, 37.966, 9.888]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={22.985}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube014.geometry}
          material={materials.window}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube014_1.geometry}
          material={materials.WINDOW}
        />
      </group>
      <group position={[-19.39, 45.742, 4.597]} scale={16.663}>
        <instances.Cube2 />
        <instances.Cube3 />
      </group>
      <group
        position={[-13.932, 27.697, -5.796]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[5.681, 5.251, 7.712]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube035.geometry}
          material={materials.WOOD}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube035_1.geometry}
          material={materials["wood dark"]}
        />
      </group>
      <group
        position={[-24.234, 45.742, 9.441]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={16.663}
      >
        <instances.Cube2 />
        <instances.Cube3 />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube063.geometry}
        material={materials.roofing}
        position={[-13.932, 27.697, -5.796]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[5.681, 5.251, 8.296]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube064.geometry}
        material={materials["wood dark"]}
        position={[-13.932, 27.697, -5.796]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[5.681, 5.251, 8.296]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube065.geometry}
        material={materials["wood dark"]}
        position={[-11.823, 27.357, -10.308]}
        scale={[3.001, 0.34, 0.34]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube066.geometry}
        material={materials["wood dark"]}
        position={[-13.932, 27.697, -5.796]}
        scale={[0.296, 0.265, 0.265]}
      />
      <instances.Cube1
        position={[-8.706, 29.121, 0.418]}
        rotation={[-0.029, -0.049, -0.125]}
        scale={[0.198, 0.198, 0.393]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube068.geometry}
        material={materials.concrete}
        position={[-16.195, 21.253, 4.121]}
        scale={[5.479, 3.481, 7.123]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube069.geometry}
        material={materials.concrete}
        position={[-4.035, 21.253, 8.904]}
        scale={[5.479, 3.481, 2.34]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube070.geometry}
        material={materials.concrete}
        position={[-4.415, 17.773, 2.161]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[5.479, 3.481, 1.802]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube071.geometry}
        material={materials.metal}
        position={[-4.035, 21.253, 8.904]}
        scale={22.985}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube072.geometry}
        material={materials.metal}
        position={[18.686, 17.638, 4.338]}
        scale={22.985}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube073.geometry}
        material={materials["wood dark"]}
        position={[-7.968, 34.97, -5.796]}
        rotation={[0, 0, -0.23]}
        scale={[0.493, 0.357, 0.274]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube074.geometry}
        material={materials.window}
        position={[-13.452, 34.726, 2.003]}
        rotation={[0, 0, -0.092]}
        scale={[3.668, 0.202, 0.202]}
      />
      <group
        position={[-8.525, 30.736, -5.79]}
        rotation={[0, 0, -0.1]}
        scale={[0.926, 0.387, 1.211]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube052_1.geometry}
          material={materials.window}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube052_2.geometry}
          material={materials.WINDOW}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube076.geometry}
        material={materials.concrete}
        position={[17.493, 5.479, -11.809]}
        rotation={[0, Math.PI / 2, 0]}
        scale={22.985}
      />
      <group
        position={[-8.525, 30.736, -1.482]}
        rotation={[0, 0, -0.1]}
        scale={[0.926, 0.387, 1.211]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube052_3.geometry}
          material={materials.window}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube052_4.geometry}
          material={materials.WINDOW}
        />
      </group>
      <group
        position={[-8.525, 30.736, -10.092]}
        rotation={[0, 0, -0.1]}
        scale={[0.926, 0.387, 1.211]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube052_5.geometry}
          material={materials.window}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube052_6.geometry}
          material={materials.WINDOW}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube079.geometry}
        material={materials.concrete}
        position={[22.74, -3.657, 2.448]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[5.479, 3.481, 2.624]}
      />
      <group position={[-14.572, 30.214, 2.003]} scale={[1.246, 1.999, 1.246]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube056_1.geometry}
          material={materials.WOOD}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube056_2.geometry}
          material={materials.WINDOW}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube056_3.geometry}
          material={materials.window}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube056_4.geometry}
          material={materials["wood dark"]}
        />
      </group>
      <group
        position={[-18.536, 30.214, 4.463]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[1.246, 1.999, 1.246]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube057_1.geometry}
          material={materials["wood dark"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube057_2.geometry}
          material={materials.WINDOW}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube057_3.geometry}
          material={materials.WOOD}
        />
      </group>
      <instances.Cube1
        position={[-8.329, 32.579, -12.088]}
        rotation={[-0.029, -0.049, -0.125]}
        scale={[0.198, 0.198, 0.393]}
        castShadow
        receiveShadow
      />
      <instances.Cube1
        position={[-8.329, 33.501, -12.829]}
        rotation={[-0.029, -0.049, -0.125]}
        scale={[0.198, 0.198, 0.393]}
        castShadow
        receiveShadow
      />
      <instances.Cube1
        position={[-8.329, 33.918, -11.31]}
        rotation={[3.109, 0.049, 0.125]}
        scale={[0.198, 0.198, 0.393]}
        castShadow
        receiveShadow
      />
      <instances.Cube1
        position={[-8.467, 31.204, -4.114]}
        rotation={[3.113, 0.049, -3.017]}
        scale={[-0.198, -0.198, -0.393]}
        castShadow
        receiveShadow
      />
      <group
        position={[-24.234, 8.815, 4.597]}
        rotation={[0, Math.PI / 8, 0]}
        scale={[7.542, 20.073, 7.542]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004_1.geometry}
          material={materials.WOOD}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004_2.geometry}
          material={materials["wood dark"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder005.geometry}
        material={materials.metal}
        position={[-24.234, 57.902, 4.597]}
        scale={[21.292, 22.985, 21.292]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder006.geometry}
        material={materials.metal}
        position={[-24.234, 10.79, 4.597]}
        scale={[21.052, 22.985, 21.052]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder007.geometry}
        material={materials.WINDOW}
        position={[-24.234, 57.902, 4.597]}
        scale={[21.292, 22.985, 21.292]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane011.geometry}
        material={materials.water}
        position={[-75.665, 75.216, -7.164]}
        scale={[22.985, 34.108, 22.985]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012.geometry}
        material={materials.Grass}
        position={[0, 20.908, 0]}
        scale={[13.683, 18.285, 18.285]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane013.geometry}
        material={materials.sand}
        position={[16.525, -1.289, 18.419]}
        rotation={[0, 0.834, 0]}
        scale={[25.633, 22.985, 22.985]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane014.geometry}
        material={materials.WINDOW}
        position={[-13.452, 33.911, 2.018]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[1.6, 1.6, 0.959]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane016.geometry}
        material={materials.bush}
        position={[3.307, 26.644, -13.453]}
        scale={22.985}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane018.geometry}
        material={materials.bush}
        position={[-0.597, 22.365, 14.419]}
        scale={22.985}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane019.geometry}
        material={materials.sand}
        position={[16.525, -1.289, 18.419]}
        rotation={[0, 0.834, 0]}
        scale={[25.633, 22.985, 22.985]}
      />
      <instances.Plant
        position={[8.196, 21.73, -15.834]}
        rotation={[0.208, -0.258, -0.252]}
        scale={[0.465, 0.504, 0.405]}
        castShadow
        receiveShadow
      />
      <instances.Plant
        position={[10.582, 21.309, -4.719]}
        rotation={[0.307, -0.391, 0.021]}
        scale={[0.465, 0.504, 0.405]}
        castShadow
        receiveShadow
      />
      <instances.Plant
        position={[-1.376, 20.957, -11.219]}
        rotation={[0.096, -0.391, -0.032]}
        scale={[0.465, 0.504, 0.405]}
        castShadow
        receiveShadow
      />
      <instances.Plant
        position={[26.052, 8.198, -14.018]}
        rotation={[-0.105, -0.454, -0.655]}
        scale={[0.465, 0.504, 0.405]}
        castShadow
        receiveShadow
      />
      <instances.Plant
        position={[21.145, 8.198, -15.716]}
        rotation={[0.181, -0.342, -0.023]}
        scale={[0.465, 0.504, 0.405]}
        castShadow
        receiveShadow
      />
      <instances.Plant
        position={[23.935, 8.198, -18.121]}
        rotation={[-0.027, 0.015, -0.221]}
        scale={[0.465, 0.504, 0.405]}
        castShadow
        receiveShadow
      />
      <instances.Plant
        position={[19.471, 8.198, -18.497]}
        rotation={[-0.027, 0.015, -0.221]}
        scale={[0.465, 0.504, 0.405]}
        castShadow
        receiveShadow
      />
      <instances.Plant
        position={[17.545, 8.343, -16.953]}
        rotation={[0.793, 1.143, -1.05]}
        scale={[0.465, 0.504, 0.405]}
        castShadow
        receiveShadow
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere001.geometry}
        material={materials.roofing}
        position={[-24.234, 58.474, 4.597]}
        scale={[3.635, 3.924, 3.635]}
      />
      <instances.Terain
        position={[-9.823, 7.317, 19.475]}
        rotation={[-Math.PI, 0.686, -Math.PI]}
        scale={[7.627, 5.781, 7.627]}
        castShadow
        receiveShadow
      />
      <instances.Terain
        position={[3.478, -2.483, 27.737]}
        rotation={[0, 0.732, 0]}
        scale={[7.627, 5.781, 7.627]}
        castShadow
        receiveShadow
      />
      <instances.Terain
        position={[15.025, -2.483, 10.979]}
        rotation={[Math.PI, -1.201, 0]}
        scale={[-7.627, -9.303, -7.627]}
        castShadow
        receiveShadow
      />
      <instances.Terain
        position={[7.813, 4.207, -3.564]}
        rotation={[0, 1.47, -Math.PI]}
        scale={[-8.663, -9.303, -7.627]}
        castShadow
        receiveShadow
      />
      <instances.Terain
        position={[-16.597, 18.916, 13.696]}
        rotation={[0, 1.377, -Math.PI]}
        scale={[-7.948, -4.593, -6.997]}
        castShadow
        receiveShadow
      />
      <instances.Terain
        position={[-8.999, 15.352, 2.902]}
        rotation={[0, -1.507, -Math.PI]}
        scale={[-7.948, -6.777, -6.997]}
        castShadow
        receiveShadow
      />
      <instances.Terain1
        position={[-9.429, 0, 28.003]}
        rotation={[-Math.PI, 0.557, -Math.PI]}
        scale={[6.07, 2.138, 6.07]}
        castShadow
        receiveShadow
      />
      <instances.Terain1
        position={[1.596, 7.034, 19.169]}
        rotation={[0, 0.791, 0]}
        scale={[6.07, 3.623, 6.07]}
        castShadow
        receiveShadow
      />
      <instances.Terain1
        position={[-8.997, 7.558, 19.246]}
        rotation={[Math.PI, -0.116, Math.PI]}
        scale={[6.07, 3.426, 6.07]}
        castShadow
        receiveShadow
      />
      <instances.Terain1
        position={[-12.615, 5.966, 26.608]}
        rotation={[-Math.PI, 0.295, -Math.PI]}
        scale={[2.68, 3.426, 2.68]}
        castShadow
        receiveShadow
      />
      <instances.Terain1
        position={[7.704, -0.104, 16.241]}
        rotation={[0, 0.791, 0]}
        scale={[6.07, 2.861, 6.07]}
        castShadow
        receiveShadow
      />
      <instances.Terain1
        position={[7.999, 5.691, 8.352]}
        rotation={[Math.PI, -1.099, Math.PI]}
        scale={[6.07, 3.943, 6.07]}
        castShadow
        receiveShadow
      />
      <instances.Terain1
        position={[9.649, 1.502, -17.599]}
        rotation={[0, -1.486, 0]}
        scale={[6.07, 5.178, 6.07]}
        castShadow
        receiveShadow
      />
      <instances.Terain1
        position={[-11.498, 17.641, -17.272]}
        rotation={[Math.PI, -1.019, Math.PI]}
        scale={[6.07, 2.579, 6.07]}
        castShadow
        receiveShadow
      />
      <instances.Terain1
        position={[-14.174, 19.738, -5.152]}
        rotation={[-Math.PI, 1.511, -Math.PI]}
        scale={[6.07, 2.15, 6.07]}
        castShadow
        receiveShadow
      />
      <instances.Terain1
        position={[-19.311, 15.619, 17.279]}
        rotation={[0, 1.095, 0]}
        scale={[6.425, 3.39, 8.782]}
        castShadow
        receiveShadow
      />
      <instances.Terain1
        position={[-22.962, 27.713, 15.732]}
        rotation={[0, -1.57, 0]}
        scale={[4.597, 1.015, 6.283]}
        castShadow
        receiveShadow
      />
      <instances.Terain1
        position={[15.041, -1.825, -3.191]}
        rotation={[0, -1.396, 0]}
        scale={[6.07, 2.834, 6.07]}
        castShadow
        receiveShadow
      />
      <instances.Terain1
        position={[17.793, -1.825, 7.462]}
        rotation={[0, 0.727, 0]}
        scale={[2.948, 4.18, 3.819]}
        castShadow
        receiveShadow
      />
      <instances.Terain1
        position={[23.187, -3.793, -15.551]}
        rotation={[-Math.PI, 0.893, -Math.PI]}
        scale={[4.43, 3.103, 4.43]}
        castShadow
        receiveShadow
      />
      <instances.Terain1
        position={[17.244, -3.793, -16.155]}
        rotation={[Math.PI, -0.134, Math.PI]}
        scale={[3.096, 3.103, 3.199]}
        castShadow
        receiveShadow
      />
      <instances.Terain1
        position={[-22.372, 0, 22.167]}
        rotation={[0, -0.572, 0]}
        scale={5.324}
      />
      <group
        position={[-13.635, 26.926, -18.323]}
        rotation={[0, 0.1, 0]}
        scale={0.513}
      >
        <instances.BzierCurve />
        <instances.BzierCurve1 />
      </group>
      <group
        position={[23.44, 7.87, -16.599]}
        rotation={[0, 0.655, 0]}
        scale={0.397}
      >
        <instances.BzierCurve />
        <instances.BzierCurve1 />
      </group>
      <group
        position={[11.469, 20.941, -16.047]}
        rotation={[Math.PI, -0.413, Math.PI]}
        scale={0.513}
      >
        <instances.BzierCurve />
        <instances.BzierCurve1 />
      </group>
      <group
        position={[8.35, 20.658, -6.152]}
        rotation={[0, 1.201, 0]}
        scale={0.409}
      >
        <instances.BzierCurve />
        <instances.BzierCurve1 />
      </group>
      <group
        position={[3.164, 20.656, 20.924]}
        rotation={[-Math.PI, 0.059, -Math.PI]}
        scale={0.333}
      >
        <instances.BzierCurve />
        <instances.BzierCurve1 />
      </group>
      <group
        position={[-9.194, 19.982, 20.338]}
        rotation={[0, -0.347, 0]}
        scale={0.457}
      >
        <instances.BzierCurve />
        <instances.BzierCurve1 />
      </group>
      <group
        position={[-8.678, 17.283, 27.907]}
        rotation={[0, 0.565, 0]}
        scale={0.409}
      >
        <instances.BzierCurve />
        <instances.BzierCurve1 />
      </group>
      <group
        position={[0.004, 19.982, -16.391]}
        rotation={[0, -1.026, 0]}
        scale={0.513}
      >
        <instances.BzierCurve />
        <instances.BzierCurve1 />
      </group>
    </group>
  );
}

useGLTF.preload("/assets/island.glb");
