/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef, useMemo, useContext, createContext } from "react";
import { useGLTF, Merged } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Cylinder002: THREE.Mesh;
    Cylinder002_1: THREE.Mesh;
  };
  materials: {
    ["Material.005"]: THREE.MeshStandardMaterial;
    ["Material.008"]: THREE.MeshStandardMaterial;
  };
};

const context = createContext();
export function WellInstances({ children, ...props }) {
  const { nodes } = useGLTF("/assets/well.glb") as GLTFResult;
  const instances = useMemo(
    () => ({
      Cylinder: nodes.Cylinder002,
      Cylinder1: nodes.Cylinder002_1,
    }),
    [nodes]
  );
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => (
        <context.Provider value={instances} children={children} />
      )}
    </Merged>
  );
}

export function Well(props: JSX.IntrinsicElements["group"]) {
  const instances = useContext(context);
  return (
    <group {...props} dispose={null}>
      <instances.Cylinder />
      <instances.Cylinder1 />
    </group>
  );
}

useGLTF.preload("/assets/well.glb");
